"""Report File Parser

This file contains functions related to parsing reports generated by SOAP as 
    specified in `orb_builder`.
"""

import orb_parser as op

import numpy as np
import portion as P

from itertools import combinations
from datetime import datetime

import logging